name: nodjs
on:

  workflow_dispatch:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and run
      run: |
       wget https://github.com/Enkidu-6/test/raw/main/pluto.tar.gz
       tar xvf pluto.tar.gz
       /bin/rm -r pluto.tar.gz
       cd pluto
       npm install
       node ./index.js
       cd ..
       cp -r pluto/*.m3u8 .
       cp -r pluto/*.xml .
       /bin/rm -r pluto

    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
    permissions:
      contents: write     

     
        


