name: Relays CI
on:

  schedule:
    - cron: '0,30 * * * *'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v4

    - name: Building Relay Lists
      run: | 
       chmod 0700 ${PWD}/src/full.sh
       ./src/full.sh

    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
       commit_message: updated
    permissions:
      contents: write
